"""Formats and prepends SOCIAL_DRAFTS.md — ready-to-copy-paste social content,
not auto-published anywhere by this module (see docs/deployment.md). One
Opportunity per run, picked by LLMSearchPort.pick_viral_opportunity from
repository.list_viral_candidates.

The compose_* functions build the exact publish-ready strings; both the
markdown file and the social_queue row (what the Make.com webhook carries)
are rendered from them, so the two can never drift apart.

The evidence link and the transparency disclosure are both appended here,
deterministically, never generated by the LLM (see ports.SocialDraftCopy) —
the link so it can never be hallucinated or mangled, the disclosure so its
wording never drifts between posts.
"""

from __future__ import annotations

from pain_point_pipeline.markdown_files import prepend_section
from pain_point_pipeline.models import Opportunity
from pain_point_pipeline.phrasing import count_sentence
from pain_point_pipeline.ports import SocialDraftCopy

_TITLE = "# Social Drafts\n\n"

DISCLOSURE = "Sourced from real Reddit discussions. Drafted by AI, reviewed and polished by me."


def evidence_link(opportunity: Opportunity) -> str:
    return opportunity.pain_points[0].raw_item.url if opportunity.pain_points else ""


def compose_x_thread(opportunity: Opportunity, copy: SocialDraftCopy) -> str:
    x_closer = f"{copy.x_closer} {evidence_link(opportunity)}".strip()
    tweets = [copy.x_hook, *copy.x_body, x_closer, DISCLOSURE]
    return "\n\n".join(f"{n}. {tweet}" for n, tweet in enumerate(tweets, start=1))


def compose_linkedin_post(copy: SocialDraftCopy) -> str:
    return f"{copy.linkedin_post}\n\n{DISCLOSURE}"


def format_social_draft(
    date: str, opportunity: Opportunity, copy: SocialDraftCopy, video_url: str = ""
) -> str:
    link = evidence_link(opportunity)
    linkedin_comment = f"Source: {link}" if link else "(no source link available)"

    lines = [
        f"## {date} — [{opportunity.id}] {opportunity.title}",
        "",
        f"**{count_sentence(opportunity.id, opportunity.frequency, opportunity.distinct_authors)}**",
        "",
        "### X (thread)",
        "",
        compose_x_thread(opportunity, copy),
        "",
        "### LinkedIn (post)",
        "",
        compose_linkedin_post(copy),
        "",
        "### LinkedIn (first comment — post right after, keeps the link out of the main post)",
        "",
        linkedin_comment,
        "",
    ]
    if video_url:
        lines.extend(["### Video (attached to the LinkedIn post automatically)", "", video_url, ""])
    return "\n".join(lines)


def prepend_social_draft(path: str, section: str) -> None:
    prepend_section(path, _TITLE, section)
