"""Formats and prepends SOCIAL_DRAFTS.md — ready-to-copy-paste social content,
not auto-published anywhere (see docs/deployment.md). One Opportunity per run,
picked by LLMSearchPort.pick_viral_opportunity from repository.list_viral_candidates.

The evidence link and the transparency disclosure are both appended here,
deterministically, never generated by the LLM (see ports.SocialDraftCopy) —
the link so it can never be hallucinated or mangled, the disclosure so its
wording never drifts between posts.
"""

from __future__ import annotations

from pain_point_pipeline.markdown_files import prepend_section
from pain_point_pipeline.models import Opportunity
from pain_point_pipeline.ports import SocialDraftCopy

_TITLE = "# Social Drafts\n\n"

DISCLOSURE = "Sourced from real Reddit discussions. Drafted by AI, reviewed and polished by me."


def _evidence_link(opportunity: Opportunity) -> str:
    return opportunity.pain_points[0].raw_item.url if opportunity.pain_points else ""


def format_social_draft(date: str, opportunity: Opportunity, copy: SocialDraftCopy) -> str:
    link = _evidence_link(opportunity)
    x_closer = f"{copy.x_closer} {link}".strip()
    tweets = [copy.x_hook, *copy.x_body, x_closer, DISCLOSURE]
    x_thread = "\n\n".join(f"{n}. {tweet}" for n, tweet in enumerate(tweets, start=1))
    linkedin_post = f"{copy.linkedin_post}\n\n{DISCLOSURE}"
    linkedin_comment = f"Source: {link}" if link else "(no source link available)"

    return "\n".join(
        [
            f"## {date} — {opportunity.title}",
            "",
            f"**{opportunity.frequency} reports from {opportunity.distinct_authors} people**",
            "",
            "### X (thread)",
            "",
            x_thread,
            "",
            "### LinkedIn (post)",
            "",
            linkedin_post,
            "",
            "### LinkedIn (first comment — post right after, keeps the link out of the main post)",
            "",
            linkedin_comment,
            "",
        ]
    )


def prepend_social_draft(path: str, section: str) -> None:
    prepend_section(path, _TITLE, section)
